authors:
  dusan:
    name: Dusan Gostimirovic
    description: Founder
    avatar: https://media.licdn.com/dms/image/v2/C4E03AQGWxb8cTGgvjg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1516680366323?e=1741824000&v=beta&t=bDdtLURRzsoGP6PtFziaMMod36_ZSY0EEEY6ZB4QavU
    url: https://www.linkedin.com/in/dusangostimirovic/
